spring:
   jmx:
      enabled: true
   boot:
      admin:
         client:
            instance:
               metadata:
                  tags:
                     environment: ${spring.profiles.active}

   zipkin:
      enabled: true
      
logging:
   file:
      name: /var/log/${spring.application.name}.log
   pattern:
      file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint}
         %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'

eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8081/eureka
   instance:
      prefer-ip-address: true
      hostname: localhost

management:
   endpoints:
      web:
         exposure:
            include: '*'
   trace:
      http:
         enabled: true

springdoc:
   show-actuator: true
