   cloud:
      config:
         server:
            git:
               uri: https://github.com/myqualitto/config.git
               cloneOnStart: true
               searchPaths: '{profile}'
               force-pull: true
               skipSslValidation: true
               default-label: master
