spring:
   boot:
      admin:
         ui:
            view-settings:
            -  name: journal
               enabled: true
            -  name: about
               enabled: false
      monitor:
         default-timeout: 60000
         status-interval: 15000
         status-lifetime: 150000
         defaultRetries: 5
